name: Deploy Flask to Azure Web App

on:
  push:
    branches: [ master, main ]

env:
  AZURE_WEBAPP_NAME: IndiciLogsAndErrors   # your app name
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create artifact
        run: |
          echo "Creating artifact"
          mkdir artifact
          shopt -s extglob
          cp -R !(venv|artifact|.git) artifact/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .
  
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: production
          package: .
