# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - indicilogsanderrors

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: indicilogsanderrors   # must match your Web App name in Azure (lowercase)
  PYTHON_VERSION: '3.11'                  # stable version supported in Azure

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add test step here (PyTest, Django test suites, etc.)

      - name: Create deployment package
        run: |
          echo "Creating artifact folder"
          mkdir artifact
          shopt -s extglob
          cp -R !(venv|artifact|.git) artifact/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: artifact/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # required for OIDC login
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BB6B987DAE841FD9BC89213ED69CC22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_688F1A8EF9234368A20E4F3ED7308B1E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_82EB8F529B734FF7A356087CD3C47BC3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: production
          package: ./artifact

